---
- hosts: localhost
  name: Setup ONTAP Cluster
  gather_facts: no
  vars_files:
  - vars/var_file.yml
  - vars/licenses.yml
  vars_prompt:
  - name: "password"
    prompt: "Password:"
  tasks:
  - name: Add licenses
    na_ontap_license:
      state: present
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
      license_codes: "{{ esx_licenses }}"
  - name: Assign unowned disks
    na_ontap_disks:
      node: "{{ item }}"
      https: true
      validate_certs: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
    with_items:
      - vsim-01
      - vsim-02
  - name: Create Aggrs
    na_ontap_aggregate:
      state: "{{ state }}"
      name: "{{ item.name }}"
      nodes: "{{ item.node }}"
      disk_count: 26
      raid_size: 26
      https: true
      validate_certs: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
    with_items:
      - { name: "aggr1", node: "vsim-01" }
      - { name: "aggr2", node: "vsim-01" }
      - { name: "aggr3", node: "vsim-02" }
      - { name: "aggr4", node: "vsim-02" }